export type HistoricalQuotation = { source: string; clientName: string; locationName: string; address: string; date: string; serviceType: string; items: { description: string; quantity: number; price: number }[] };
export const historicalQuotations: HistoricalQuotation[] = [
  { source: "Edificio vandergerh.0309.docx", clientName: "Edificio Vandergerh", locationName: "Jorge Vandergerh 389", address: "Jorge Vandergerh 389", date: "2026-09-03", serviceType: "Inyectado asistido noche y madrugada", items: [{ description: "Movilización de Lima", quantity: 1, price: 50 }, { description: "Técnico y mano de obra noche y madrugada", quantity: 1, price: 320 }] },
  { source: "Grupo santa Elena hilasaca.0409.docx", clientName: "Grupo Santa Elena Hilasaca", locationName: "Cañete Quilmaná", address: "Cañete / Quilmaná", date: "2026-09-04", serviceType: "Acompañamiento Osinergmin", items: [{ description: "Movilización de Lima a Cañete", quantity: 1, price: 150 }, { description: "Mano de obra y viáticos", quantity: 1, price: 280 }] },
  { source: "Redondos Plantel 256 Toshi.2708.docx", clientName: "Redondos Plantel 256 Toshi", locationName: "Vegueta Huaura Huacho", address: "Vegueta, Huaura, Huacho", date: "2026-08-27", serviceType: "Mantenimiento de 14 tanques", items: [{ description: "Movilización de Lima a Huaral y retorno", quantity: 1, price: 300 }, { description: "Pintado de 13 tanques de 1000 galones", quantity: 1, price: 8450 }, { description: "Pintado de tanque de 120 galones", quantity: 1, price: 400 }, { description: "Hospedaje para 2 personas", quantity: 1, price: 400 }, { description: "Movilización interna para granja", quantity: 1, price: 90 }, { description: "Viáticos", quantity: 1, price: 400 }] },
  { source: "Redondos Toshi 5.0809.docx", clientName: "Redondos Toshi 5", locationName: "Vegueta Huaura", address: "Vegueta, Huaura", date: "2026-09-08", serviceType: "Tubería matriz rota", items: [{ description: "Movilización de Lima a Huaura", quantity: 1, price: 250 }, { description: "Reparación, accesorios y 2 atenciones", quantity: 1, price: 500 }] },
  { source: "Redondos Toshi 6, Toshi 3, Toshi 5.0809.docx", clientName: "Redondos Toshi 6 Toshi 3 y Toshi 5", locationName: "Vegueta Huaura", address: "Vegueta, Huaura", date: "2026-09-08", serviceType: "Tuberías rotas", items: [{ description: "Movilización de Lima a Huaura", quantity: 1, price: 250 }, { description: "Reparaciones, accesorios y personal", quantity: 1, price: 500 }] },
  { source: "San Fernando plantel 261.0709.docx", clientName: "San Fernando Plantel 261", locationName: "Chancay Huaral", address: "Chancay - Huaral", date: "2026-09-07", serviceType: "Tubería rota", items: [{ description: "Movilización de Lima", quantity: 1, price: 200 }, { description: "Personal, accesorios y electrofusión", quantity: 1, price: 480 }] },
  { source: "San Fernando plantel 271.0209.docx", clientName: "San Fernando Plantel 271", locationName: "Huaral Huacho Lima", address: "Huaral - Huacho - Lima", date: "2026-09-02", serviceType: "Mantenimiento de 10 tanques", items: [{ description: "Movilización de Lima a Huacho y retorno", quantity: 1, price: 300 }, { description: "Pintado de 2 tanques de 1000 galones", quantity: 1, price: 1300 }, { description: "Lavado y pintado de línea de consumo de 8 tanques", quantity: 1, price: 800 }, { description: "Movilización interna", quantity: 1, price: 30 }, { description: "Hospedaje para 2 personas", quantity: 1, price: 100 }, { description: "Viáticos para 2 personas", quantity: 1, price: 160 }] },
  { source: "San Fernando- plantel 127.0309.docx", clientName: "San Fernando Plantel 127", locationName: "Asia Cañete Lima", address: "Asia - Cañete - Lima", date: "2026-09-03", serviceType: "Acompañamiento Osinergmin", items: [{ description: "Movilización de Lima a Cañete y retorno", quantity: 1, price: 220 }, { description: "Pintado de 12 tanques de 1000 galones", quantity: 1, price: 7800 }, { description: "Pintado de tanque de 250 galones", quantity: 1, price: 435 }, { description: "Movilización interna de 3 días", quantity: 1, price: 90 }, { description: "Hospedaje", quantity: 1, price: 300 }, { description: "Viáticos para 2 personas", quantity: 1, price: 320 }] },
];
